### ISSUE TITLE
We need more unicorns!

### ISSUE THREAD

**Issue by pjsawicki** [kubernetes-sigs/contributor-playground#118]
We need to have more unicorns in this repo!

**Comment by annehwatson** [comment]
+1

**Comment by cezarygerard** [comment]
unbelievable...

**Comment by stevemcquaid** [comment]
Duplicate of:

#126
#131
#137

/triage duplicate

**Comment by fejta** [comment]
Please see https://github.com/kubernetes/test-infra/issues/10415 where we are working on something similar.

**Comment by Katharine** [comment]
We have more unicorns now.

/pony unicorn
