### ISSUE TITLE
Not enough animal photos in presentations

### ISSUE THREAD

**Issue by mikekim** [kubernetes-sigs/contributor-playground#131]
/kind bug
KubeCon Seattle 2018 presentation slides do not have enough animal pictures in them.

I searched the existing issues and couldn't find anything about it. Sorry if it's a duplicate.

**Comment by CsatariGergely** [comment]
Isn't bug an animal?

**Comment by stevemcquaid** [comment]
Duplicate of:
#118
#126
#137

/triage duplicate

**Comment by cchengleo** [comment]
#126

**Comment by guineveresaenger** [comment]
Don't encourage me.

KITTENS ALL THE WAY 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 🐈 

/close
