### ISSUE TITLE
README.md needs more cowbell

### ISSUE THREAD

**Issue by stevemcquaid** [kubernetes-sigs/contributor-playground#137]
The README.md located here:https://github.com/rcbops/kubecon2018/blob/master/README.md
Does not have enough cowbell. It affects UX and morale for all developers.

**Comment by magaldima** [comment]
this needs a kind maybe `/kind bug`

**Comment by stevemcquaid** [comment]
Duplicate of:
- https://github.com/kubernetes-sigs/contributor-playground/issues/118
- https://github.com/kubernetes-sigs/contributor-playground/issues/126
- https://github.com/kubernetes-sigs/contributor-playground/issues/131
- https://github.com/kubernetes-sigs/contributor-playground/issues/137

/triage duplicate

**Comment by guineveresaenger** [comment]
Closing this for cleanup - remember you can always `/reopen` if you like!

/close
