### ISSUE TITLE
Hello Kubecon!

### ISSUE THREAD

**Issue by soggiest** [kubernetes-sigs/contributor-playground#144]
We lost some of our team members though

**Comment by rajathagasthya** [comment]
What is the fix for the issue?

**Comment by soggiest** [comment]
Track them down and chain them to the table?

**Comment by agamdua** [comment]
They'll be back. They know where the cool kids are.

**Comment by vikramk7** [comment]
I will fix this.

**Comment by rajathagasthya** [comment]
Works for me.

**Comment by guineveresaenger** [comment]
Closing this for cleanup - remember you can always `/reopen` if you like!

/close
