### ISSUE TITLE
Unable to support the IPv6 connection between the PODs

### ISSUE THREAD

**Issue by jdjgya** [kubernetes-sigs/contributor-playground#150]
### Summary
Unable to support the IPv6 connection between the PODs

### Reproducible
100%

 ### Steps
1.
2.
3.
.....

 ### Release
1.12.0

**Comment by Cryptophobia** [comment]
> ### Release
> 
> 1.12.0

Release 1.13.0 is already out we should have this feature in roadmap for 1.14.0 :+1:

**Comment by jdjgya** [comment]
¯\_(ツ)_/¯

**Comment by guineveresaenger** [comment]
Closing this for cleanup - remember you can always `/reopen` if you like!

/close
