### ISSUE TITLE
Access to all slides from New Contributor and Contributor Conference?

### ISSUE THREAD

**Issue by allenstecat** [kubernetes-sigs/contributor-playground#208]
Access to all slides from New Contributor and Contributor Conference?

/sig contributor-experience
@guineveresaenger

**Comment by guineveresaenger** [comment]
PR being worked on here: https://github.com/kubernetes-sigs/contributor-playground/pull/213

in the meantime, please see https://github.com/cncf/presentations/tree/master/kubernetes

**Comment by guineveresaenger** [comment]
Closing this via #213!
