### ISSUE TITLE
This is an issue exercise

### ISSUE THREAD

**Issue by mdianjun** [kubernetes-sigs/contributor-playground#22]
/kind bug

**Comment by mdianjun** [comment]
sig/scheduling

**Comment by mdianjun** [comment]
king/bug

**Comment by mdianjun** [comment]
@flaper87

**Comment by mdianjun** [comment]
@markselby9   How to remove a label?

**Comment by markselby9** [comment]
@mdianjun I'm trying the commands from: https://prow.k8s.io/command-help

**Comment by guineveresaenger** [comment]
Closing this for cleanup purposes
/close
