### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by amarnathkarthik** [kubernetes-sigs/contributor-playground#223]
Add more documentation

**Comment by guineveresaenger** [comment]
what happens if I don't start with a slash: /sig contributor-experience

**Comment by jberkus** [comment]
What kind of documentation?  What's missing?

**Comment by guineveresaenger** [comment]
Here we would discuss details; talk, suggest, find time to hack, come up with a plan to fix the documentation.

**Comment by v-gachary** [comment]
/ assgin @v-gachary
