### ISSUE TITLE
This is a really emergency issue!!!

### ISSUE THREAD

**Issue by godliness** [kubernetes-sigs/contributor-playground#27]
/kind bug
/sig contributor-experience
/sig scheduling
/sig node
/sig release
/area example

/cc @k8s-ci-robot

**Comment by mdianjun** [comment]
> /kind bug
> /sig contributor-experience
> /sig scheduling
> /sig node

**Comment by mdianjun** [comment]
> /kind bug
> /sig contributor-experience
> /sig scheduling
> /sig node

Yes, you are right!

**Comment by godliness** [comment]
¯\_(ツ)_/¯
