### ISSUE TITLE
Issue created from KubeConf Shanghai by Samuel and David

### ISSUE THREAD

**Issue by niyue** [kubernetes-sigs/contributor-playground#33]

**Comment by dwmkerr** [comment]
OK @niyue just checking you have signed the CLA

**Comment by dwmkerr** [comment]
In the meantime I will take this on /assign @qbl

**Comment by dwmkerr** [comment]
Seems like this issue has too many cats, will hold for now

**Comment by guineveresaenger** [comment]
Closing this for cleanup purposes
/close
