### ISSUE TITLE
this is a title

### ISSUE THREAD

**Issue by jiaj12** [kubernetes-sigs/contributor-playground#53]
/label documentation

**Comment by tpepper** [comment]
I'm sorry, I explained wrong.  The Prow /commands (see https://prow.k8s.io/command-help) set appropriate labels.

In this case "/sig docs".

**Comment by tpepper** [comment]
So it is more structured instead of allowing an arbitrary "/label some_string".   There is more details of what are valid labels hidden inside https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

**Comment by tpepper** [comment]
The common ones you are likely to use are "kind", "sig", and "area".

**Comment by guineveresaenger** [comment]
Closing this for cleanup purposes
/close
