### ISSUE TITLE
Check and update contents of prerequisites on Japan event

### ISSUE THREAD

**Issue by atoato88** [kubernetes-sigs/contributor-playground#635]
Japan member will hold [kubernetes training on 10, March](https://github.com/kubernetes-sigs/contributor-playground/tree/master/japan/cndo-2021).

For that event, we need to check and update (if any) contents of [prerequisites](https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md) and other assets.

@s-ito-ts 
We ensure that doesn't include old contents or need to add additional steps. 
Could you check the content of [prerequisites](https://github.com/kubernetes-sigs/contributor-playground/blob/master/japan/assets/attendee-prerequisites.md)?

/assign @s-ito-ts

**Comment by s-ito-ts** [comment]
@atoato88 
I checked that there are no problems. (Don't need to update or add.)

**Comment by atoato88** [comment]
@s-ito-ts 
Thank you to quick checking contents.
I've created PR #636 which updates prerequisite file because of adding more ease reading for attendee.

Could you review that?
