### ISSUE TITLE
adding a gitignore file 

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes-sigs/contributor-playground#814]
Sometimes folks unknowingly commit some temp files along with their changes, for example `.DS_Store` in the case of macOS users. It will be easier for new contributors if we have a `.gitignore` file which excludes all such files. 

See #775

**Comment by RinkiyaKeDad** [comment]
You can read more about `.gitignore` files here - https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

You can see an example of a `.gitignore` file here - https://github.com/kubernetes/enhancements/blob/master/.gitignore

**Comment by Lakshya8066** [comment]
Hey @RinkiyaKeDad 
Can I take the issue if no one is working on it?

**Comment by Edge2Ops** [comment]
> Hey @RinkiyaKeDad
> Can I take the issue if no one is working on it?

Hey @Lakshya8066 
Just give me a day, will update on this here :)

**Comment by RinkiyaKeDad** [comment]
Hey @Lakshya8066, since @Edge2Ops are still working on this could you please unassign yourself? You can find more `good-first-issues` [here](https://www.google.com/url?q=https://go.k8s.io/good-first-issue&sa=D&source=editors&ust=1627298948995000&usg=AOvVaw3E4xJLNiC7_E0-m8-Eg-aQ) 🙂

**Comment by Lakshya8066** [comment]
Hey @Edge2Ops @RinkiyaKeDad, sorry for the inconvenience.

**Comment by Edge2Ops** [comment]
> Hey @Edge2Ops @RinkiyaKeDad, sorry for the inconvenience.
No worries @Lakshya8066  :)

**Comment by lakshya8066** [comment]
Hey, can I assign myself if no one is working on it?

**Comment by Edge2Ops** [comment]
Ah' my bad. Just saw it. Will update it right away, thanks !

**Comment by lakshya8066** [comment]
No problem @Edge2Ops. Go ahead :)

**Comment by MadhavJivrajani** [comment]
Hey sorry - removing and re-applying these labels to test out a PR that was just merged for the bot

/remove-good-first-issue
/remove-help

**Comment by RinkiyaKeDad** [comment]
Hey @Edge2Ops are you still interested in working on this? 🙂

**Comment by Edge2Ops** [comment]
Hey @RinkiyaKeDad  Yes, I need to rebase my PR.
Will update and let you know asap
